### ISSUE TITLE
Add comment client paging support

### ISSUE THREAD

**Issue by gsidebo** [mitodl/edx-username-changer#11]
The results that are returned by the openedx comment client are paged, and this app does not account for that paging. As a result, we only inspect the first 20 threads or comments that a user has been involved in. It's possible that the paging was added after we created this app.

**Implementation:**

These are the functions I used to debug this issue locally and fix a single user. If you use this code, just replace the existing `get_authored_threads_and_comments` function instead of naming it `get_authored_threads_and_comments_v2` as I did here.

```python
course_id = '...'
user = User.objects.get(username='...')
#
def get_involved_threads(course_id, user_id):
  page = 0
  involved_threads = []
  while len(involved_threads) > 0 or page == 0:
    involved_threads = [ 
      Thread.find(id=thread["id"]).retrieve(
        with_responses=True, recursive=True, mark_as_read=False
      )
      for thread in Thread.search(
        {"course_id": course_id, "user_id": comment_user.id, "page": page}
      ).collection
    ]
    yield from involved_threads
    page += 1
#
def get_authored_threads_and_comments_v2(comment_user, enrolled_course_ids):
  for course_id in enrolled_course_ids:
    involved_threads = get_involved_threads(course_id, comment_user.id)
    for thread in involved_threads:
      if thread["user_id"] == comment_user.id:
        yield thread.to_dict()
      children_to_scan = thread["children"]
      while children_to_scan:
         child = children_to_scan.pop(0)
         children_to_scan.extend(child["children"])
         if child["user_id"] == comment_user.id:
            yield child
```

**Comment by arslanashraf7** [comment]
This fix is available in the new package([0.3.0](https://pypi.org/project/edx-username-changer/0.3.0/)) is out as well, Closed via #12.
