### ISSUE TITLE
Add test framework and linting

### ISSUE THREAD

**Issue by HamzaIbnFarooq** [mitodl/edx-username-changer#2]
### Description
The plugin is in working form but basic stuff like Testing, Github Actions, and Quality checks are not in place right now. Thus this issue is meant to add all the basic features to the plugin.

### Acceptance Criteria
- [x] Enable testing
- [x] Add Quality related plugins
- [x] Enable CI using github actions 

### Note
It would be better if we inherit the plugin with [cookiecutter-django-app](https://github.com/edx/edx-cookiecutters/tree/master/cookiecutter-django-app)

**Comment by arslanashraf7** [comment]
Closing, This ticket is not directly related to a prod deployment so I'm closing it on associated PR's merge.
